fix: earthfile: Also copy the `examples` dir
Otherwise `earthly +build_dev` will complain with:
```
error: failed to parse manifest at `/wolfssl-sys/Cargo.toml`

Caused by:
  can't find `connect_pq` example at `examples/connect_pq.rs` or `examples/connect_pq/main.rs`...
```